# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
opt_out_usage
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "holo-wtf.xcodeproj")
    build_app(scheme: "holo-wtf")
    upload_to_testflight
  end

  lane :tests do
    run_tests(scheme: "holo-wtf")
  end

  lane :sentry do
    build_app(scheme: "holo-wtf")
    sentry_upload_dif(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: ENV['SENTRY_ORG'],
      project_slug: 'holo-wtf',
      include_sources: true,
      path: '.'
    )
  end
end
